### ISSUE TITLE
Broken image in READme

### ISSUE THREAD

**Issue by shannonbux** [datocms/gatsby-portfolio#12] opened 2020-01-29 00:56 UTC
## Problem

Very small issue, but when I used this starter via Gatsby Cloud, the screenshot in the READme of my copy of the starter seems broken.

https://github.com/shannonbux/dato-cms-test-1-23

**Comment by matjack1** [comment] 2020-01-29 09:47
Yes, I've seen this, very strange! Looks like the image gets corrupted on project duplication.

I'll try to reproduce and understand where the problem is.

**Comment by shannonbux** [comment] 2020-01-29 18:15
Thanks for looking into it, Matteo!

**Comment by matjack1** [comment] 2020-03-12 13:28
Looks like it's fixed now. Thank you for the report. If you experience this again please reopen!

**Closed as completed by matjack1** 2020-03-12 13:28 UTC
Labels: bug

**Comment by shannonbux** [comment] 2020-03-12 23:37
Thank you Matteo!

**Comment by matjack1** [comment] 2020-03-18 15:48
@shannonbux actually yesterday I've noticed that happening again, but it only happens from Gatsby Cloud.

If I start a demo from DatoCMS it works just fine: https://github.com/matjack1/datocms-Gatsby-portfolio-demo-2

not sure what's happening on your side, but I confirm that it's still broken, sorry! :(

If you have something else that is working correctly I can try to find the differences.

**Comment by shannonbux** [comment] 2020-03-18 20:20
Thank you @matjack1! This page shows the other Cloud starters; the Contentful is actually the only one with a complete and bug-free READme file. https://www.gatsbyjs.com/get-started/. I've also reached out to the Cloud team to make sure it's not a bug on our end.

**Comment by matjack1** [comment] 2020-03-19 14:49
@shannonbux the Contentful one works because they are referencing an image from another repo: https://rawgit.com/contentful-userland/gatsby-contentful-starter/master/screenshot.jpg

the screenshot in the cloned repo by Gatsby Cloud is corrupted also for them: https://github.com/shannonbux/dfjas-dlfjasldkfj/blob/master/screenshot.jpg

I think it's something off on your end :(

**Comment by shannonbux** [comment] 2020-03-19 22:21
You're right, I told the team and it is on our end! Thanks!
